# -*- coding: utf-8 -*-
"""face_recognition.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rf0USLPFafybXqveIhmrBIor4uBOGNU-
"""

import face_recognition
import pandas as pd
import os

import numpy as np

test_dir  = './test_dataset'
test_data = os.listdir(test_dir)
# test_data.sort()
# train_data[:10]

train_dir = './train_dataset'
train_data = os.listdir(train_dir)
train_data.sort()

encodings_list = pd.DataFrame()
encodings_list['Person'] = []
encodings_list['encoding'] = []

"""Trained for classified faces

"""

for i in train_data[1:]:
  image = face_recognition.load_image_file(os.path.join(train_dir ,i))
  face_encoding_list = face_recognition.face_encodings(image, model='cnn')
  encodings_list.loc[len(encodings_list)] = [i.split('.')[0], face_encoding_list[0]]

result = pd.DataFrame()
result['S.No'] = []
for i in encodings_list['Person']:
  result[i] = []
  result[i] = result[i].astype(int)

#result

for i in test_data:
  image = face_recognition.load_image_file(os.path.join(test_dir ,i))
  face_encoding_list = face_recognition.face_encodings(image, model='cnn')

  if len(face_encoding_list) > 0:
      dict__ = []

      for j in face_encoding_list:
        matches = face_recognition.compare_faces(list(encodings_list['encoding']), j)
        dict__.append([int(item) for item in matches])

      dict__ = np.asarray(dict__)

      for k in dict__[1:]:
        dict__[0] += k

      final__dict = [i]

      for ele in dict__[0]:
        final__dict.append(int(ele))

      result.loc[len(result)] = final__dict
  else:
    result.loc[len(result)] = [i , 0, 0, 0, 0, 0, 0]

result

result.to_csv('result.csv')